Adding Virus_total_key argument
Ostorlab/agent_subfinder pull request #27
Opened 2024-12-02 11:38 UTC by PiranhaSa

In this PR I've added the support for virustotal api key , so subfinder can use it . we can do that by adding the key to the provider-config.yaml conf file . 
![image](https://github.com/user-attachments/assets/4b19c50f-d31c-4ff7-ac93-e918275de217)

2024-12-03 08:42 UTC, amine3 submitted a review, later dismissed

2024-12-03 08:42 UTC, amine3 commented on agent/subfinder_agent.py
> +    config_path: str = "/root/.config/subfinder/provider-config.yaml",
Use a const

2024-12-03 08:42 UTC, amine3 commented on agent/subfinder_agent.py
> +    config_path: str = "/root/.config/subfinder/provider-config.yaml",
Based on the documentation, the default is  $CONFIG/subfinder/config.yaml no?

2024-12-04 07:52 UTC, PiranhaSa commented on agent/subfinder_agent.py
> +    config_path: str = "/root/.config/subfinder/provider-config.yaml",
From the dockerfile I saw that we have 
![image](https://github.com/user-attachments/assets/73853748-4070-48aa-8fd4-c6cb90094114)
and from their doc it doesn't say config.yaml : 
![image](https://github.com/user-attachments/assets/420571cc-0b66-4e84-801e-fc13d5400ce0)

2024-12-04 14:45 UTC, Zakaria-Latif commented on agent/subfinder_agent.py
> +from ruamel.yaml import YAML
```suggestion
from ruamel import yaml 
```

2024-12-05 07:39 UTC, PiranhaSa commented on agent/subfinder_agent.py
> +from ruamel.yaml import YAML
The name of the package is ruamel.yaml so I did change it to be import ruamel.yaml

2024-12-05 08:01 UTC, nmasdoufi-ol reviewed
LGTM

2024-12-05 09:02 UTC, 3asm requested changes

2024-12-05 09:02 UTC, 3asm commented on tests/subfinder_agent_test.py
> +    assert "Failed to write configuration file" in caplog.text
I don't see unit test for the `update_provider_config` when the write is working?

2024-12-05 09:02 UTC, 3asm commented on agent/subfinder_agent.py
> +            update_provider_config(virustotal_key)
The name doesn't match what the method is doing. The method is just about virustotal.

2024-12-06 11:09 UTC, 3asm approved these changes

2024-12-06 11:10 UTC, merged